version: '3.8'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.react_server
    container_name: rank-tracker-server
    volumes:
      - node_modules:/code/node_modules  # store the node modules in a volume
      - ./src:/code/src
    ports:
      - "3000:3000"
    depends_on:
      - flask

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask-serp-api
    volumes:
      - ./backend:/code/backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  node_modules:
  redis_data:
