# Use the official Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /code

# Install Flask and flask-cors
RUN pip install Flask flask-cors serpapi redis gunicorn

# Copy the app code into the container
COPY flask_api.py .

# Expose port 5000 for the Flask app
EXPOSE 5000

# Run the app
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "flask_api:app"]
